---
- name: Configure host and puma on reddit-app
  hosts: app
  become: true
  vars:
    db_host: 10.132.15.210
  tasks:
    - name: Add unit file for Puma
      copy: src=files/puma.service dest=/etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/avzakharov77/db_config
        owner: avzakharov77
        group: avzakharov77

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: 
      name: puma
      daemon_reload: yes
      state: restarted

