---
- name: Configure mongo on reddit-db
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted

- name: Configure host and puma on reddit-app
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.132.15.208
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/avzakharov77/db_config
        owner: avzakharov77
        group: avzakharov77

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    become: true
    service: name=puma state=restarted

- name: Deploy application code
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Fetch the latest version of application code of puma
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/avzakharov77/reddit
        version: monolith
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/avzakharov77/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted


