---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.15.200
  tasks:
    - name: Fetch the latest version of application code of puma
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/avzakharov77/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/avzakharov77/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Bundle install
#      become: true
      bundler:
#        executable: /usr/bin
        state: present
        chdir: /home/avzakharov77/reddit
      tags: deploy-tag

  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
    tags: restmongo

  - name: reload puma
    become: true
    systemd: name=puma state=restarted
    tags: restpuma
